<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'HM_Backup' => $vendorDir . '/humanmade/hm-backup/hm-backup.php',
);
